server:
  port: 8089 #端口号




#---
#开发环境
#server:
#  port: 8091
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#---
##生产环境
#server:
#  port: 8092
#spring:
#  config:
#    activate:
#      on-profile: prod
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    username: bdc_vc_rw_dev
    password: ip0agASfil6Z
    url: jdbc:mysql://172.29.1.100:5000/bd_cloud_vehicle_dev?useUnicode=false&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml


