#开发环境
server:
  port: 8091
  servlet:
    context-path: /in-dev

#日志级别

#使用相对路径的方式设置日志输出的位置（项目根目录目录\my-log\mylog\spring.log）
#logging.file.path=my-log/myLog
#绝对路径方式将日志文件输出到 【项目所在磁盘根目录\springboot\logging\my\spring.log】
#控制台日志输出格式
#日志文件输出格式
logging:
  file:
    path: /resources/logging
